name = "Flash's NPCs"
filename = "flashnpcs-1.16.5-1.1.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3626/737/flashnpcs-1.16.5-1.1.4.jar"
hash-format = "sha1"
hash = "96ccb2f485ba7eb0d512283c446139f552d11a2d"

[update]
[update.curseforge]
file-id = 3626737
project-id = 517167
